spring:
  application:
    name: springboot-kong

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: health, httptrace
  endpoint:
    health:
      show-details: always